// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function teamToJs(param) {
  return {
          size: param[/* size */0],
          m: param[/* m */1],
          p: param[/* p */2]
        };
}

function teamFromJs(param) {
  return /* record */[
          /* size */param.size,
          /* m */param.m,
          /* p */param.p
        ];
}

function getTeamPerson(param) {
  return param[/* p */2][/* name */1];
}

var mixedTeam = /* record */[
  /* size */3,
  /* m : record */[
    /* age */1,
    /* hasTentacles */false
  ],
  /* p : record */[
    /* age */22,
    /* name */"Bob"
  ]
];

var a = /* Army */[
  /* Monster */Block.__(1, [/* record */[
        /* age */30,
        /* hasTentacles */true
      ]]),
  /* ArmyMembers */[/* Monster */Block.__(1, [/* record */[
          /* age */12,
          /* hasTentacles */false
        ]])]
];

var b = /* Army */[
  /* Person */Block.__(0, [/* record */[
        /* age */30,
        /* name */"Ghengis Khan"
      ]]),
  /* ArmyMembers */[/* Person */Block.__(0, [/* record */[
          /* age */12,
          /* name */"Bob"
        ]])]
];

function serializeTeam(param) {
  var match = param[/* p */2];
  var match$1 = param[/* m */1];
  return {
          hasTentacles: match$1[/* hasTentacles */1],
          age: match$1[/* age */0],
          person: {
            name: match[/* name */1],
            age: match[/* age */0]
          },
          size: param[/* size */0]
        };
}

var j = { };

j["name"] = "Bob";

j["age"] = 4.3;

console.log(JSON.stringify(j));

console.log(b);

console.log(a);

console.log(getTeamPerson(mixedTeam));

console.log(serializeTeam(mixedTeam));

console.log(teamToJs(mixedTeam));

console.log(mixedTeam);

var c = /* Army */[
  /* Person */Block.__(0, [/* record */[
        /* age */30,
        /* name */"Ghengis Khan"
      ]]),
  /* ArmyMembers */[/* Monster */Block.__(1, [/* record */[
          /* age */12,
          /* hasTentacles */false
        ]])]
];

exports.teamToJs = teamToJs;
exports.teamFromJs = teamFromJs;
exports.getTeamPerson = getTeamPerson;
exports.mixedTeam = mixedTeam;
exports.a = a;
exports.b = b;
exports.c = c;
exports.serializeTeam = serializeTeam;
exports.j = j;
/*  Not a pure module */
